language: r
sudo: required
cache: packages
dist: trusty

warnings_are_errors: false

notifications:
  email:
    - leo.lahti@iki.fi

r_packages:
  - Cairo
  - rgdal
  - gdalUtils
  - sf
  - V8
  - geojsonio
  - geojsonlint
  - mapview
  - rmapshaper
  - tmap
  - tmaptools  
  
r_github_packages:
  - jimhester/covr

env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - r_build_args: "--no-resave-data"
  - r_check_args: "--as-cran"    
  - GITHUB_REPO: ropengov/eurostat

before_install:
  - pip install --user codecov
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libv8-dev
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev

r:
- release
- devel
- oldrel

after_success:
  - Rscript -e 'covr::codecov()'

