language: r
sudo: required
cache: packages
dist: trusty

warnings_are_errors: false

notifications:
  email:
    - leo.lahti@iki.fi



r_packages:
  - broom
  - Cairo
  - classInt
  - curl  
  - devtools
  - ggplot2
  - httr
  - jsonlite
  - knitr  
  - lubridate  
  - gdalUtils
  - geojson  
  - geojsonio
  - geojsonlint
  - jqr    
  - mapview
  - mapproj
  - plotrix
  - protolite
  - rgdal
  - RColorBrewer
  - readr
  - rmarkdown
  - rmapshaper  
  - roxygen2
  - rsdmx
  - rvest  
  - sf
  - sp  
  - tmap
  - tmaptools  
  - testthat
  - V8
  
r_github_packages:
  - jimhester/covr

env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - GITHUB_REPO: ropengov/eurostat

r_build_args: "--no-resave-data --no-build-vignettes"
r_check_args: "--as-cran --no-build-vignettes"    

apt_packages:
  - libudunits2-dev
  - udunits2
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - libcairo2-dev
  - protobuf-compiler
  - valgrind
  - libgdal20
  - libspatialite-dev 
  - libproj-dev
  - libgeos-dev
  - libgdal1-dev
  - libgdal-dev
  - libgeos-c1v5
  - libjq-dev
  - netcdf-bin

before_install:


  - pip install --user codecov
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get --yes install npm
  - Rscript -e 'install.packages("broom",repos="http://cran.us.r-project.org")'
  - Rscript -e 'install.packages("classInt", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("curl", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("httr", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("jsonlite", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("RColorBrewer", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
  - Rscript -e 'install.packages("sf", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("sp", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("readr", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("Cairo", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("ggplot2", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("lubridate", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("mapproj", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("plotrix", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("rmarkdown", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("roxygen2", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("rsdmx", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("rvest", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("testthat", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'
 - Rscript -e 'install.packages("tmap", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'                      
  - Rscript -e 'install.packages("knitr", repos="http://cran.us.r-project.org", lib="/home/travis/R-bin/lib/R/library/")'  

install:
  - . $HOME/.nvm/nvm.sh  
  - nvm install stable
  - nvm use stable
  - npm install -g mapshaper
  - npm install -g geojson  

r:
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'


