language: r
sudo: required
cache: packages
dist: trusty

warnings_are_errors: false

notifications:
  email:
    - leo.lahti@iki.fi

r_packages:
  - broom
  - Cairo
  - devtools
  - libcairo2-dev
  - gdalUtils
  - geojson  
  - geojsonio
  - geojsonlint
  - jsonlite
  - jqr    
  - mapview  
  - protolite
  - rgdal    
  - rmapshaper
  - sf  
  - tmap
  - tmaptools  
  - V8
  - knitr
  
r_github_packages:
  - jimhester/covr

env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - r_build_args: "--no-resave-data --no-build-vignettes"
  - r_check_args: "--as-cran"    
  - GITHUB_REPO: ropengov/eurostat

apt_packages:
  - libudunits2-dev
  - udunits2
  - libv8-dev
  - libprotobuf-dev
  - libprotoc-dev
  - libcairo2-dev
  - protobuf-compiler
  - valgrind
  - libgdal20
  - libspatialite-dev 
  - libproj-dev
  - libgeos-dev
  - libgdal1-dev
  - libgdal-dev
  - libgeos-c1v5
  - libjq-dev
  - netcdf-bin

before_install:
  - pip install --user codecov
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get --yes install npm
  - Rscript -e 'install.packages("broom",repos="http://cran.us.r-project.org")'
#  - Rscript -e 'install.packages("knitr",repos="http://cran.us.r-project.org")'

install:
  - . $HOME/.nvm/nvm.sh  
  - nvm install stable
  - nvm use stable
  - npm install -g mapshaper
  - npm install -g geojson  

r:
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'


